In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

F:\python\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
F:\python\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
F:\python\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
data=pd.read_csv("X_train.csv")
test_data=pd.read_csv("X_test.csv")
data1=pd.read_csv("y_train.csv")

In [3]:
data.head()

id  moons  feature_1  feature_2  feature_3  feature_4  \
0  0x5314efb4ebe6edb3      0       0.00       0.00       0.00       0.25   
1  0xdce321dc608a6e75      0       0.50       0.00       0.25       0.00   
2   0x5638d323a6eb0d6      0       0.00       0.00       0.00       0.00   
3  0x76913fe81685babe      0       0.25       0.25       0.25       0.25   
4  0xadb2bb2a7f67542f      0       0.50       1.00       1.00       1.00   

   feature_5  feature_6  feature_7  feature_8  ...  feature_20  feature_21  \
0       0.25       0.25       0.00       0.25  ...        1.00        0.00   
1       0.25       0.25       0.75       0.50  ...        0.50        0.25   
2       0.00       0.00       0.50       0.25  ...        0.50        0.00   
3       0.25       0.25       0.50       0.75  ...        0.50        0.50   
4       1.00       1.00       0.50       0.25  ...        0.75        1.00   

   feature_22  feature_23  feature_24  feature_25  feature_26  feature_27  \
0        0.25        0.25        1.00        0.75        0.25        0.50   
1        0.00        0.50        0.00        1.00        0.00        0.25   
2        0.00        0.00        0.75        0.00        1.00        1.00   
3        0.25        0.25        0.50        0.75        0.00        0.00   
4        1.00        1.00        1.00        0.50        1.00        1.00   

   feature_28  feature_29  
0        0.50        0.50  
1        1.00        1.00  
2        0.50        0.50  
3        1.00        0.75  
4        0.75        0.50  

[5 rows x 31 columns]

In [4]:
test_data.head()

id  moons  feature_1  feature_2  feature_3  feature_4  \
0   0x3f93da0d2cc6818     44        1.0       0.75       0.50       0.75   
1  0x219dd207b662ad77     44        0.0       0.75       0.75       0.75   
2  0xa6ed4d2ed10b42c9     44        1.0       1.00       1.00       1.00   
3  0xee2c52b87f235083     44        1.0       0.25       0.25       0.25   
4  0x1748d58e711b9066     44        1.0       1.00       1.00       1.00   

   feature_5  feature_6  feature_7  feature_8  ...  feature_20  feature_21  \
0       0.75       1.00       0.50       0.75  ...         0.0        0.75   
1       0.50       0.50       0.50       0.50  ...         0.0        0.25   
2       1.00       1.00       0.75       0.50  ...         0.0        0.50   
3       0.25       0.25       0.50       0.50  ...         0.0        0.50   
4       0.75       0.75       0.75       0.50  ...         0.0        0.50   

   feature_22  feature_23  feature_24  feature_25  feature_26  feature_27  \
0        0.75        0.75        0.00        0.00        0.50        1.00   
1        0.50        0.25        0.75        0.50        0.25        0.50   
2        1.00        0.75        1.00        0.75        0.50        0.25   
3        0.50        0.25        0.50        0.00        0.25        0.25   
4        0.75        0.75        0.50        0.00        0.00        0.50   

   feature_28  feature_29  
0        0.50        0.75  
1        0.25        0.25  
2        0.50        0.25  
3        0.75        0.75  
4        0.00        0.25  

[5 rows x 31 columns]

In [5]:
xtrain=data.drop('id',axis=1)
xtrain=xtrain.drop('moons',axis=1)

In [6]:
xtrain

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0           0.00       0.00       0.00       0.25       0.25       0.25   
1           0.50       0.00       0.25       0.00       0.25       0.25   
2           0.00       0.00       0.00       0.00       0.00       0.00   
3           0.25       0.25       0.25       0.25       0.25       0.25   
4           0.50       1.00       1.00       1.00       1.00       1.00   
...          ...        ...        ...        ...        ...        ...   
91070       0.00       0.00       0.00       0.00       0.00       0.00   
91071       0.50       0.25       0.25       0.25       0.25       0.25   
91072       1.00       0.25       0.50       0.25       0.00       0.00   
91073       0.75       0.25       0.25       0.25       0.50       0.50   
91074       0.00       0.25       0.25       0.50       0.50       0.50   

       feature_7  feature_8  feature_9  feature_10  ...  feature_20  \
0           0.00       0.25       0.50        0.50  ...        1.00   
1           0.75       0.50       0.00        0.00  ...        0.50   
2           0.50       0.25       0.00        0.00  ...        0.50   
3           0.50       0.75       0.25        0.25  ...        0.50   
4           0.50       0.25       1.00        1.00  ...        0.75   
...          ...        ...        ...         ...  ...         ...   
91070       0.50       0.25       0.00        0.00  ...        0.00   
91071       0.75       0.75       0.00        0.25  ...        0.00   
91072       1.00       0.75       0.00        0.50  ...        0.25   
91073       0.75       0.25       0.00        0.25  ...        0.00   
91074       0.00       0.25       0.50        0.50  ...        0.00   

       feature_21  feature_22  feature_23  feature_24  feature_25  feature_26  \
0            0.00        0.25        0.25        1.00        0.75        0.25   
1            0.25        0.00        0.50        0.00        1.00        0.00   
2            0.00        0.00        0.00        0.75        0.00        1.00   
3            0.50        0.25        0.25        0.50        0.75        0.00   
4            1.00        1.00        1.00        1.00        0.50        1.00   
...           ...         ...         ...         ...         ...         ...   
91070        0.00        0.00        0.00        1.00        0.50        0.25   
91071        0.50        0.25        0.25        0.75        0.50        0.75   
91072        0.50        0.00        0.00        1.00        1.00        0.50   
91073        0.25        0.00        0.25        1.00        0.50        1.00   
91074        0.00        0.25        0.00        1.00        0.00        0.50   

       feature_27  feature_28  feature_29  
0            0.50        0.50        0.50  
1            0.25        1.00        1.00  
2            1.00        0.50        0.50  
3            0.00        1.00        0.75  
4            1.00        0.75        0.50  
...           ...         ...         ...  
91070        0.50        0.50        0.25  
91071        0.50        0.25        0.75  
91072        0.50        0.50        0.25  
91073        0.75        0.00        0.25  
91074        1.00        0.25        0.00  

[91075 rows x 29 columns]

In [7]:
xtest=test_data.drop('id',axis=1)
xtest=xtest.drop('moons',axis=1)

In [8]:
xtest

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0           1.00       0.75       0.50       0.75       0.75       1.00   
1           0.00       0.75       0.75       0.75       0.50       0.50   
2           1.00       1.00       1.00       1.00       1.00       1.00   
3           1.00       0.25       0.25       0.25       0.25       0.25   
4           1.00       1.00       1.00       1.00       0.75       0.75   
...          ...        ...        ...        ...        ...        ...   
48532       0.75       0.50       0.50       0.50       0.50       0.50   
48533       0.00       0.00       0.00       0.00       0.00       0.00   
48534       1.00       0.75       0.75       0.75       0.75       0.75   
48535       0.00       0.00       0.00       0.00       0.00       0.00   
48536       1.00       1.00       1.00       1.00       1.00       1.00   

       feature_7  feature_8  feature_9  feature_10  ...  feature_20  \
0           0.50       0.75       0.75        1.00  ...        0.00   
1           0.50       0.50       0.75        0.75  ...        0.00   
2           0.75       0.50       1.00        1.00  ...        0.00   
3           0.50       0.50       0.50        0.25  ...        0.00   
4           0.75       0.50       1.00        1.00  ...        0.00   
...          ...        ...        ...         ...  ...         ...   
48532       0.50       0.00       0.50        0.50  ...        0.50   
48533       0.00       0.00       0.00        0.00  ...        0.50   
48534       0.75       0.00       0.75        0.75  ...        0.50   
48535       0.75       0.00       0.00        0.00  ...        0.75   
48536       0.25       1.00       1.00        1.00  ...        1.00   

       feature_21  feature_22  feature_23  feature_24  feature_25  feature_26  \
0            0.75        0.75        0.75        0.00        0.00        0.50   
1            0.25        0.50        0.25        0.75        0.50        0.25   
2            0.50        1.00        0.75        1.00        0.75        0.50   
3            0.50        0.50        0.25        0.50        0.00        0.25   
4            0.50        0.75        0.75        0.50        0.00        0.00   
...           ...         ...         ...         ...         ...         ...   
48532        0.00        0.50        0.50        0.75        1.00        0.50   
48533        0.00        0.00        0.00        0.50        1.00        1.00   
48534        0.00        0.25        0.25        0.25        0.75        0.00   
48535        0.00        0.00        0.00        1.00        1.00        1.00   
48536        1.00        1.00        1.00        0.75        1.00        1.00   

       feature_27  feature_28  feature_29  
0            1.00        0.50        0.75  
1            0.50        0.25        0.25  
2            0.25        0.50        0.25  
3            0.25        0.75        0.75  
4            0.50        0.00        0.25  
...           ...         ...         ...  
48532        0.00        0.00        0.00  
48533        1.00        0.00        0.00  
48534        0.75        0.00        0.00  
48535        1.00        0.00        0.00  
48536        0.75        0.50        0.50  

[48537 rows x 29 columns]

In [9]:
from sklearn.decomposition import PCA
pc=PCA(n_components=2)
xtrain=pc.fit_transform(xtrain)
xtest=pc.fit_transform(xtest)
print(xtrain)

[[-1.13199165  0.51826352]
 [-1.50653175 -0.69215683]
 [-2.08968133  0.11226272]
 ...
 [-0.81560273 -0.98907366]
 [-1.06835117  0.13338485]
 [-0.8225414   1.10245853]]


In [10]:
xtest

array([[ 1.06285197, -0.27274785],
       [ 0.26611031, -0.63328949],
       [ 2.03926661, -0.28639151],
       ...,
       [ 0.29176977, -0.748232  ],
       [-2.09526528, -0.17206088],
       [ 2.17391874,  0.29505989]])

In [11]:
from sklearn.model_selection import train_test_split
xt,xte,yt,yte=train_test_split(xtrain,data1,test_size=0.2,random_state=7)

In [12]:
xt.shape

(72860, 2)

In [13]:
xte.shape

(18215, 2)

In [14]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(xt,yt)
ypred=lr.predict(xte)

In [15]:
from sklearn.metrics import mean_squared_error as mse
np.sqrt(mse(ypred,yte))

0.30777420894752305

In [26]:
yfinal=lr.predict(xtest)

In [27]:
yfinal

array([[0.38809853, 0.34442548, 0.30182127],
       [0.41093873, 0.39072927, 0.39333472],
       [0.31051399, 0.23093065, 0.14339346],
       ...,
       [0.39642402, 0.37347082, 0.37752979],
       [0.64519609, 0.71855987, 0.81998668],
       [0.36332774, 0.28795597, 0.18081128]])

In [28]:
yfinal.max()

0.9085299783402063

In [29]:
yfinal=pd.DataFrame(yfinal,columns=['target_r','target_g','target_b'])


In [30]:
yfinal

target_r  target_g  target_b
0      0.388099  0.344425  0.301821
1      0.410939  0.390729  0.393335
2      0.310514  0.230931  0.143393
3      0.561320  0.582185  0.601109
4      0.333468  0.267619  0.201091
...         ...       ...       ...
48532  0.452436  0.455455  0.492069
48533  0.605232  0.675126  0.790690
48534  0.396424  0.373471  0.377530
48535  0.645196  0.718560  0.819987
48536  0.363328  0.287956  0.180811

[48537 rows x 3 columns]

In [31]:
yfinal.to_csv("pred.csv")